/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package poker

fun main() {

    val cardx = arrayListOf(Card("Queen", "Hearts"))
    val cardy = arrayListOf(Card("Queen", "Hearts"))
    // println(Card("Queen", "Hearts").equals(Card("Queen", "Hearts")))
    println(cardx.equals(cardy))
}
